steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=sample-app']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/qwiklabs-gcp-02-36532bc8e7b0/my-repository/sample-app:v2.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/qwiklabs-gcp-02-36532bc8e7b0/my-repository/sample-app:v2.0']
- name: 'gcr.io/cloud-builders/gkubectl'
  args: ['apply', '-f', 'prod/deployment.yaml', '-n', 'prod']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
options:
  logging: CLOUD_LOGGING_ONLY
